//! ASP.NET Core and Node (Express/Fastify/NestJS) framework route SPECS.
//!
//! Authored metadata for [`super::super::StructuralFactPatternSpec`] entries.
//! Public registry access remains through
//! [`super::super::structural_fact_pattern_specs`].

use super::super::{
    ALWAYS, ARR, K_FRAMEWORK, K_PATTERN_VERSION, K_QUERY_FAMILY, OPT, STR,
    StructuralFactPatternSpec, key,
};

pub(super) const SPECS: &[StructuralFactPatternSpec] = &[
    StructuralFactPatternSpec {
        pattern_id: "aspnet.minimal_api.route.v1",
        languages: &["csharp"],
        query_family: "framework",
        description: "An ASP.NET Core minimal-API endpoint route (MapGet/MapPost/…).",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key(
                "api_style",
                STR,
                ALWAYS,
                "Routing style; \"minimal_api\" for Map* endpoint calls.",
            ),
            key(
                "verb",
                STR,
                ALWAYS,
                "HTTP method derived from the Map* call (GET/POST/PUT/PATCH/DELETE).",
            ),
            key(
                "route_template",
                STR,
                ALWAYS,
                "Raw route string passed as the first Map* argument.",
            ),
            key(
                "normalized_route_template",
                STR,
                ALWAYS,
                "Cross-family join key with a leading slash and ASP.NET route parameters converted to :param form.",
            ),
            key(
                "route_source",
                STR,
                ALWAYS,
                "Origin of the parsed route literal (\"string_literal\").",
            ),
            key(
                "route_group_prefix",
                STR,
                OPT,
                "Prefix contributed by an enclosing MapGroup, when found.",
            ),
            key(
                "effective_route_template",
                STR,
                OPT,
                "Group prefix joined with the route template, when a prefix is found.",
            ),
            key(
                "route_group_source",
                STR,
                OPT,
                "How the group prefix was resolved (\"map_group\"), when found.",
            ),
            key(
                "handler_kind",
                STR,
                OPT,
                "Handler expression shape (\"lambda\" or \"method_group\"), when parsed.",
            ),
            key(
                "handler_name",
                STR,
                OPT,
                "Dotted identifier path of a method-group handler.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "aspnet.minimal_api.route_group.v1",
        languages: &["csharp"],
        query_family: "framework",
        description: "An ASP.NET Core minimal-API `MapGroup` route group.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key("api_style", STR, ALWAYS, "Routing style (\"minimal_api\")."),
            key(
                "route_prefix",
                STR,
                ALWAYS,
                "Route prefix string passed to MapGroup(...).",
            ),
            key(
                "normalized_route_template",
                STR,
                ALWAYS,
                "Cross-family join key for the group prefix with ASP.NET route parameters converted to :param form.",
            ),
            key(
                "route_source",
                STR,
                ALWAYS,
                "Origin of the parsed prefix literal (\"string_literal\").",
            ),
            key(
                "source_kind",
                STR,
                ALWAYS,
                "Construct that produced the group (\"map_group\").",
            ),
            key(
                "group_variable",
                STR,
                OPT,
                "Variable the MapGroup result is assigned to, for linking child routes.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "aspnet.attribute_route.v1",
        languages: &["csharp"],
        query_family: "framework",
        description: "An ASP.NET Core attribute-routing fact ([Route]/[Http*] on controllers or actions).",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key(
                "api_style",
                STR,
                ALWAYS,
                "Routing style (\"attribute_routing\").",
            ),
            key(
                "attribute_kind",
                STR,
                ALWAYS,
                "Fact kind (\"controller_route\", \"http_method\", or \"route\").",
            ),
            key(
                "route_template",
                STR,
                OPT,
                "Raw template from the attribute's string-literal argument.",
            ),
            key(
                "effective_route_template",
                STR,
                OPT,
                "Controller+method template joined and token-substituted.",
            ),
            key(
                "normalized_route_template",
                STR,
                OPT,
                "Cross-family join key computed from the effective route template when present, else the raw route template.",
            ),
            key(
                "route_tokens",
                ARR,
                OPT,
                "Tokens actually substituted (\"controller\"/\"action\").",
            ),
            key(
                "verb",
                STR,
                OPT,
                "HTTP method for Http* verb attributes; absent on plain [Route] facts.",
            ),
            key(
                "controller_route_template",
                STR,
                OPT,
                "Owning controller's [Route] template attached to a method fact.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "express.route.v1",
        languages: &["javascript", "jsx", "typescript", "tsx"],
        query_family: "framework",
        description: "A static Express route registration on an in-file traced app/router receiver.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key(
                "api_style",
                STR,
                ALWAYS,
                "Routing style (\"call_routing\").",
            ),
            key(
                "route_template",
                STR,
                ALWAYS,
                "Raw static route path passed to the Express registration call.",
            ),
            key(
                "normalized_route_template",
                STR,
                ALWAYS,
                "Cross-family join key with a leading slash and Express :param segments preserved.",
            ),
            key(
                "dynamic_segments",
                ARR,
                OPT,
                "Route parameter names discovered in the normalized template.",
            ),
            key(
                "verb",
                STR,
                OPT,
                "HTTP method for verb-restricted registrations; omitted for app.all.",
            ),
            key(
                "verb_source",
                STR,
                OPT,
                "How the verb was attested (\"attested\" for Express verb methods).",
            ),
            key(
                "route_group_prefix",
                STR,
                OPT,
                "Same-file app.use mount prefix resolved onto a router route.",
            ),
            key(
                "effective_route_template",
                STR,
                OPT,
                "Mount prefix joined with the route template when same-file resolution applies.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "express.router_mount.v1",
        languages: &["javascript", "jsx", "typescript", "tsx"],
        query_family: "framework",
        description: "A static Express app.use/router.use mount point with a literal mount path.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key(
                "mount_path",
                STR,
                ALWAYS,
                "Raw static mount path passed as the first app.use argument.",
            ),
            key(
                "normalized_mount_path",
                STR,
                ALWAYS,
                "Cross-family normalized mount path.",
            ),
            key(
                "mount_target",
                STR,
                ALWAYS,
                "Source text of the mounted router or middleware expression.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "fastify.route.v1",
        languages: &["javascript", "jsx", "typescript", "tsx"],
        query_family: "framework",
        description: "A static Fastify shorthand or object-form route registration.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key(
                "api_style",
                STR,
                ALWAYS,
                "Routing style (\"call_routing\").",
            ),
            key(
                "route_template",
                STR,
                ALWAYS,
                "Raw static route path passed to the Fastify registration.",
            ),
            key(
                "normalized_route_template",
                STR,
                ALWAYS,
                "Cross-family join key with Fastify :param segments preserved.",
            ),
            key(
                "dynamic_segments",
                ARR,
                OPT,
                "Route parameter names discovered in the normalized template.",
            ),
            key(
                "verb",
                STR,
                OPT,
                "HTTP method for verb-restricted registrations; omitted for all-method registrations.",
            ),
            key(
                "verb_source",
                STR,
                OPT,
                "How the verb was attested (\"attested\" for Fastify method names or method properties).",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "nestjs.route.v1",
        languages: &["javascript", "typescript"],
        query_family: "framework",
        description: "A static NestJS HTTP-method decorator route joined to its @Controller class prefix.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key(
                "api_style",
                STR,
                ALWAYS,
                "Routing style (\"decorator_routing\").",
            ),
            key(
                "route_template",
                STR,
                ALWAYS,
                "Raw static path from the method HTTP decorator; empty for a bare @Get().",
            ),
            key(
                "normalized_route_template",
                STR,
                ALWAYS,
                "Cross-family join key with a leading slash and NestJS :param segments preserved.",
            ),
            key(
                "dynamic_segments",
                ARR,
                OPT,
                "Route parameter names discovered in the normalized template.",
            ),
            key(
                "class_route_template",
                STR,
                OPT,
                "Static @Controller class prefix (string, { path }, or array element).",
            ),
            key(
                "effective_route_template",
                STR,
                OPT,
                "Class @Controller prefix joined with the method sub-path when a static prefix applies.",
            ),
            key(
                "verb",
                STR,
                OPT,
                "Uppercase HTTP method; omitted for @All (accepts any method).",
            ),
            key(
                "verb_source",
                STR,
                OPT,
                "How the verb was attested (\"attested\" from the decorator name).",
            ),
        ],
    },
];
