//! ASP.NET Core, EF Core, and Node (Express/Fastify/NestJS) framework SPECS.
//!
//! Authored metadata for [`super::super::StructuralFactPatternSpec`] entries.
//! Public registry access remains through
//! [`super::super::structural_fact_pattern_specs`].

use super::super::{
    ALWAYS, ARR, K_FRAMEWORK, K_PATTERN_VERSION, K_QUERY_FAMILY, OPT, STR,
    StructuralFactPatternSpec, key,
};

pub(super) const SPECS: &[StructuralFactPatternSpec] = &[
    StructuralFactPatternSpec {
        pattern_id: "aspnet.minimal_api.route.v1",
        languages: &["csharp", "fsharp", "razor", "vbnet"],
        query_family: "framework",
        description: "An ASP.NET Core minimal-API endpoint route (MapGet/MapPost/…).",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key(
                "api_style",
                STR,
                ALWAYS,
                "Routing style; \"minimal_api\" for Map* endpoint calls.",
            ),
            key(
                "verb",
                STR,
                OPT,
                "Static HTTP method from a Map* call or MapMethods collection; omitted when unknown.",
            ),
            key(
                "verb_source",
                STR,
                OPT,
                "Unknown when the methods expression cannot be resolved statically.",
            ),
            key(
                "route_template",
                STR,
                ALWAYS,
                "Raw route string passed as the first Map* argument.",
            ),
            key(
                "normalized_route_template",
                STR,
                ALWAYS,
                "Cross-family join key with a leading slash and ASP.NET route parameters converted to :param form.",
            ),
            key(
                "route_source",
                STR,
                ALWAYS,
                "Origin of the parsed route literal (\"string_literal\").",
            ),
            key(
                "route_group_prefix",
                STR,
                OPT,
                "Prefix contributed by an enclosing MapGroup, when found.",
            ),
            key(
                "effective_route_template",
                STR,
                OPT,
                "Group prefix joined with the route template, when a prefix is found.",
            ),
            key(
                "route_group_source",
                STR,
                OPT,
                "How the group prefix was resolved (\"map_group\"), when found.",
            ),
            key(
                "handler_kind",
                STR,
                OPT,
                "Handler expression shape (\"lambda\" or \"method_group\"), when parsed.",
            ),
            key(
                "handler_name",
                STR,
                OPT,
                "Dotted identifier path of a method-group handler.",
            ),
            key(
                "endpoint_kind",
                STR,
                OPT,
                "Verb-less endpoint map: \"signalr_hub\" (MapHub), \"any_verb\" (Map), or \"health_checks\" (MapHealthChecks); absent on verb maps.",
            ),
            key(
                "hub_type",
                STR,
                OPT,
                "Hub class named by the MapHub generic argument.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "aspnet.minimal_api.route_group.v1",
        languages: &["csharp", "razor", "vbnet"],
        query_family: "framework",
        description: "An ASP.NET Core minimal-API `MapGroup` route group.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key("api_style", STR, ALWAYS, "Routing style (\"minimal_api\")."),
            key(
                "route_prefix",
                STR,
                ALWAYS,
                "Route prefix string passed to MapGroup(...).",
            ),
            key(
                "normalized_route_template",
                STR,
                ALWAYS,
                "Cross-family join key for the group prefix with ASP.NET route parameters converted to :param form.",
            ),
            key(
                "route_source",
                STR,
                ALWAYS,
                "Origin of the parsed prefix literal (\"string_literal\").",
            ),
            key(
                "source_kind",
                STR,
                ALWAYS,
                "Construct that produced the group (\"map_group\").",
            ),
            key(
                "group_variable",
                STR,
                OPT,
                "Variable the MapGroup result is assigned to, for linking child routes.",
            ),
            key(
                "parent_route_prefix",
                STR,
                OPT,
                "Effective prefix of the group this MapGroup is called on, when nested.",
            ),
            key(
                "effective_route_template",
                STR,
                OPT,
                "Parent prefix joined with this group's prefix, when nested.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "aspnet.attribute_route.v1",
        languages: &["csharp", "fsharp", "vbnet"],
        query_family: "framework",
        description: "An ASP.NET attribute-routing fact ([Route]/[RoutePrefix]/[Http*] on controllers or actions).",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key(
                "api_style",
                STR,
                ALWAYS,
                "Routing style (\"attribute_routing\").",
            ),
            key(
                "attribute_kind",
                STR,
                ALWAYS,
                "Fact kind (\"controller_route\", \"http_method\", or \"route\").",
            ),
            key(
                "route_template",
                STR,
                OPT,
                "Raw template from the attribute's string-literal argument.",
            ),
            key(
                "effective_route_template",
                STR,
                OPT,
                "Controller+method template joined and token-substituted.",
            ),
            key(
                "normalized_route_template",
                STR,
                OPT,
                "Cross-family join key computed from the effective route template when present, else the raw route template.",
            ),
            key(
                "route_tokens",
                ARR,
                OPT,
                "Tokens actually substituted (\"controller\"/\"action\").",
            ),
            key(
                "verb",
                STR,
                OPT,
                "HTTP method for Http* verb attributes, one fact per AcceptVerbs verb; absent on plain [Route] facts.",
            ),
            key(
                "controller_route_template",
                STR,
                OPT,
                "Owning controller's [Route] template attached to a method fact.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "giraffe.route.v1",
        languages: &["fsharp"],
        query_family: "framework",
        description: "A Giraffe combinator route (`route`, `routef`, `routeStartsWith`, `subRoute` and their Ci forms).",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key(
                "api_style",
                STR,
                ALWAYS,
                "Routing style (\"combinator_routing\").",
            ),
            key(
                "route_function",
                STR,
                ALWAYS,
                "The Giraffe routing function name.",
            ),
            key(
                "route_template",
                STR,
                ALWAYS,
                "Raw string-literal template passed to the routing function.",
            ),
            key(
                "route_group_prefix",
                STR,
                OPT,
                "Joined prefixes of the enclosing `subRoute` calls.",
            ),
            key(
                "effective_route_template",
                STR,
                OPT,
                "The group prefix joined with the route template, when nested.",
            ),
            key(
                "normalized_route_template",
                STR,
                ALWAYS,
                "Cross-family join key; `routef` format specifiers normalize to `:argN` segments.",
            ),
            key(
                "verb",
                STR,
                OPT,
                "HTTP method from an enclosing `GET >=>`-style verb handler; omitted when none.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "aspnet.conventional_route.v1",
        languages: &["csharp", "vbnet"],
        query_family: "framework",
        description: "An ASP.NET conventional MVC route (MapControllerRoute/MapAreaControllerRoute/MapDefaultControllerRoute).",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key(
                "api_style",
                STR,
                ALWAYS,
                "Routing style (\"conventional_routing\").",
            ),
            key(
                "route_template",
                STR,
                ALWAYS,
                "Route pattern with {controller}/{action} tokens and defaults.",
            ),
            key(
                "route_name",
                STR,
                OPT,
                "Route name from the name argument (\"default\" for MapDefaultControllerRoute).",
            ),
            key(
                "area_name",
                STR,
                OPT,
                "Area from MapAreaControllerRoute's areaName argument.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "efcore.db_set.v1",
        languages: &["csharp"],
        query_family: "framework",
        description: "An Entity Framework Core `DbSet<T>` property on a context class.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key(
                "context_type",
                STR,
                ALWAYS,
                "Class that declares the DbSet property.",
            ),
            key("property_name", STR, ALWAYS, "Name of the DbSet property."),
            key(
                "entity_type",
                STR,
                ALWAYS,
                "Entity type argument of DbSet<T>.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "efcore.table_mapping.v1",
        languages: &["csharp"],
        query_family: "framework",
        description: "An Entity Framework Core entity-to-table mapping (ToTable(\"t\") or [Table(\"t\")]).",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key("entity_type", STR, ALWAYS, "Mapped entity type."),
            key("table_name", STR, ALWAYS, "Table name string literal."),
            key(
                "mapping_source",
                STR,
                ALWAYS,
                "Origin: \"model_builder_entity\" (Entity<T>().ToTable), \"entity_type_builder\" (EntityTypeBuilder<T> parameter), or \"table_attribute\".",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "efcore.entity_configuration.v1",
        languages: &["csharp"],
        query_family: "framework",
        description: "An Entity Framework Core `IEntityTypeConfiguration<T>` class.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key(
                "configuration_type",
                STR,
                ALWAYS,
                "Configuration class name.",
            ),
            key(
                "entity_type",
                STR,
                ALWAYS,
                "Configured entity type argument.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "express.route.v1",
        languages: &["javascript", "jsx", "typescript", "tsx"],
        query_family: "framework",
        description: "A static Express route registration on an in-file traced app/router receiver.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key(
                "api_style",
                STR,
                ALWAYS,
                "Routing style (\"call_routing\").",
            ),
            key(
                "route_template",
                STR,
                ALWAYS,
                "Raw static route path passed to the Express registration call.",
            ),
            key(
                "normalized_route_template",
                STR,
                ALWAYS,
                "Cross-family join key with a leading slash and Express :param segments preserved.",
            ),
            key(
                "dynamic_segments",
                ARR,
                OPT,
                "Route parameter names discovered in the normalized template.",
            ),
            key(
                "verb",
                STR,
                OPT,
                "HTTP method for verb-restricted registrations; omitted for app.all.",
            ),
            key(
                "verb_source",
                STR,
                OPT,
                "How the verb was attested (\"attested\" for Express verb methods).",
            ),
            key(
                "route_group_prefix",
                STR,
                OPT,
                "Same-file app.use mount prefix resolved onto a router route.",
            ),
            key(
                "effective_route_template",
                STR,
                OPT,
                "Mount prefix joined with the route template when same-file resolution applies.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "express.router_mount.v1",
        languages: &["javascript", "jsx", "typescript", "tsx"],
        query_family: "framework",
        description: "A static Express app.use/router.use mount point with a literal mount path.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key(
                "mount_path",
                STR,
                ALWAYS,
                "Raw static mount path passed as the first app.use argument.",
            ),
            key(
                "normalized_mount_path",
                STR,
                ALWAYS,
                "Cross-family normalized mount path.",
            ),
            key(
                "mount_target",
                STR,
                ALWAYS,
                "Source text of the mounted router or middleware expression.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "fastify.route.v1",
        languages: &["javascript", "jsx", "typescript", "tsx"],
        query_family: "framework",
        description: "A static Fastify shorthand or object-form route registration.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key(
                "api_style",
                STR,
                ALWAYS,
                "Routing style (\"call_routing\").",
            ),
            key(
                "route_template",
                STR,
                ALWAYS,
                "Raw static route path passed to the Fastify registration.",
            ),
            key(
                "normalized_route_template",
                STR,
                ALWAYS,
                "Cross-family join key with Fastify :param segments preserved.",
            ),
            key(
                "dynamic_segments",
                ARR,
                OPT,
                "Route parameter names discovered in the normalized template.",
            ),
            key(
                "verb",
                STR,
                OPT,
                "HTTP method for verb-restricted registrations; omitted for all-method registrations.",
            ),
            key(
                "verb_source",
                STR,
                OPT,
                "How the verb was attested (\"attested\" for Fastify method names or method properties).",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "koa.route.v1",
        languages: &["javascript", "typescript"],
        query_family: "framework",
        description: "A static Koa Router route registration on a router built from `@koa/router` or `koa-router`.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key(
                "api_style",
                STR,
                ALWAYS,
                "Routing style (\"call_routing\").",
            ),
            key(
                "route_template",
                STR,
                ALWAYS,
                "Raw static route path passed to the router method.",
            ),
            key(
                "normalized_route_template",
                STR,
                ALWAYS,
                "Cross-family join key with the router prefix applied and :param segments preserved.",
            ),
            key(
                "dynamic_segments",
                ARR,
                OPT,
                "Route parameter names discovered in the normalized template.",
            ),
            key(
                "verb",
                STR,
                OPT,
                "HTTP method for verb-restricted registrations; omitted for router.all.",
            ),
            key(
                "verb_source",
                STR,
                OPT,
                "How the verb was attested (\"attested\" for router verb methods).",
            ),
            key(
                "route_group_prefix",
                STR,
                OPT,
                "Literal `prefix` option of the router constructor.",
            ),
            key(
                "effective_route_template",
                STR,
                OPT,
                "Router prefix joined with the route template.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "hapi.route.v1",
        languages: &["javascript", "typescript"],
        query_family: "framework",
        description: "A static Hapi `server.route` object-form route on a server built by `Hapi.server` or `new Hapi.Server`.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key(
                "api_style",
                STR,
                ALWAYS,
                "Routing style (\"call_routing\").",
            ),
            key(
                "route_template",
                STR,
                ALWAYS,
                "Raw static `path` of the route object.",
            ),
            key(
                "normalized_route_template",
                STR,
                ALWAYS,
                "Cross-family join key with Hapi {param} segments normalized to :param.",
            ),
            key(
                "dynamic_segments",
                ARR,
                OPT,
                "Route parameter names discovered in the normalized template.",
            ),
            key(
                "verb",
                STR,
                OPT,
                "HTTP method from the `method` property; omitted for `*`.",
            ),
            key(
                "verb_source",
                STR,
                OPT,
                "How the verb was attested (\"attested\" for the method property).",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "nestjs.route.v1",
        languages: &["javascript", "typescript"],
        query_family: "framework",
        description: "A static NestJS HTTP-method decorator route joined to its @Controller class prefix.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key(
                "api_style",
                STR,
                ALWAYS,
                "Routing style (\"decorator_routing\").",
            ),
            key(
                "route_template",
                STR,
                ALWAYS,
                "Raw static path from the method HTTP decorator; empty for a bare @Get().",
            ),
            key(
                "normalized_route_template",
                STR,
                ALWAYS,
                "Cross-family join key with a leading slash and NestJS :param segments preserved.",
            ),
            key(
                "dynamic_segments",
                ARR,
                OPT,
                "Route parameter names discovered in the normalized template.",
            ),
            key(
                "class_route_template",
                STR,
                OPT,
                "Static @Controller class prefix (string, { path }, or array element).",
            ),
            key(
                "effective_route_template",
                STR,
                OPT,
                "Class @Controller prefix joined with the method sub-path when a static prefix applies.",
            ),
            key(
                "verb",
                STR,
                OPT,
                "Uppercase HTTP method; omitted for @All (accepts any method).",
            ),
            key(
                "verb_source",
                STR,
                OPT,
                "How the verb was attested (\"attested\" from the decorator name).",
            ),
        ],
    },
];
