//! Spring, Go net/http-family, and Rails framework route SPECS.
//!
//! Authored metadata for [`super::super::StructuralFactPatternSpec`] entries.
//! Public registry access remains through
//! [`super::super::structural_fact_pattern_specs`].

use super::super::{
    ALWAYS, ARR, K_FRAMEWORK, K_PATTERN_VERSION, K_QUERY_FAMILY, OPT, STR,
    StructuralFactPatternSpec, key,
};

pub(super) const SPECS: &[StructuralFactPatternSpec] = &[
    StructuralFactPatternSpec {
        pattern_id: "spring.request_mapping.v1",
        languages: &["java", "kotlin"],
        query_family: "framework",
        description: "A Spring MVC request-mapping annotation on a class or method.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key(
                "api_style",
                STR,
                ALWAYS,
                "Routing style (\"annotation_routing\").",
            ),
            key(
                "attribute_kind",
                STR,
                ALWAYS,
                "class_route/http_method/request_mapping shape.",
            ),
            key("route_template", STR, ALWAYS, "Raw static route template."),
            key(
                "normalized_route_template",
                STR,
                ALWAYS,
                "Cross-family normalized route template.",
            ),
            key(
                "dynamic_segments",
                ARR,
                OPT,
                "Route parameter names discovered in the normalized template.",
            ),
            key(
                "class_route_template",
                STR,
                OPT,
                "Nearest class-level route template.",
            ),
            key(
                "effective_route_template",
                STR,
                OPT,
                "Class and method templates joined.",
            ),
            key(
                "verb",
                STR,
                OPT,
                "Uppercase HTTP method when verb-restricted.",
            ),
            key("verb_source", STR, OPT, "How the verb was attested."),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "go.net_http.route.v1",
        languages: &["go"],
        query_family: "framework",
        description: "A Go net/http Handle or HandleFunc route registration.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key("api_style", STR, ALWAYS, "Routing style (\"mux_routing\")."),
            key(
                "route_template",
                STR,
                ALWAYS,
                "Route path portion of the pattern.",
            ),
            key(
                "normalized_route_template",
                STR,
                ALWAYS,
                "Cross-family normalized route template.",
            ),
            key(
                "dynamic_segments",
                ARR,
                OPT,
                "Route parameter names discovered in the normalized template.",
            ),
            key(
                "host",
                STR,
                OPT,
                "Host portion when the Go 1.22+ pattern is host-scoped.",
            ),
            key(
                "verb",
                STR,
                OPT,
                "Method prefix when the Go pattern names one.",
            ),
            key("verb_source", STR, OPT, "How the verb was attested."),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "gin.route.v1",
        languages: &["go"],
        query_family: "framework",
        description: "A gin route registration on a traced router or group receiver.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key(
                "api_style",
                STR,
                ALWAYS,
                "Routing style (\"call_routing\").",
            ),
            key("route_template", STR, ALWAYS, "Raw static route path."),
            key(
                "normalized_route_template",
                STR,
                ALWAYS,
                "Cross-family normalized route template.",
            ),
            key(
                "dynamic_segments",
                ARR,
                OPT,
                "Route parameter names discovered in the normalized template.",
            ),
            key("route_group_prefix", STR, OPT, "Same-file group prefix."),
            key(
                "effective_route_template",
                STR,
                OPT,
                "Group prefix joined with route template.",
            ),
            key("verb", STR, OPT, "Uppercase HTTP method."),
            key("verb_source", STR, OPT, "How the verb was attested."),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "echo.route.v1",
        languages: &["go"],
        query_family: "framework",
        description: "An echo route registration on a traced Echo or group receiver.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key(
                "api_style",
                STR,
                ALWAYS,
                "Routing style (\"call_routing\").",
            ),
            key("route_template", STR, ALWAYS, "Raw static route path."),
            key(
                "normalized_route_template",
                STR,
                ALWAYS,
                "Cross-family normalized route template.",
            ),
            key(
                "dynamic_segments",
                ARR,
                OPT,
                "Route parameter names discovered in the normalized template.",
            ),
            key("route_group_prefix", STR, OPT, "Same-file group prefix."),
            key(
                "effective_route_template",
                STR,
                OPT,
                "Group prefix joined with route template.",
            ),
            key("verb", STR, OPT, "Uppercase HTTP method."),
            key("verb_source", STR, OPT, "How the verb was attested."),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "rails.route.v1",
        languages: &["ruby"],
        query_family: "framework",
        description: "A Rails routes DSL handler route.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key("api_style", STR, ALWAYS, "Routing style (\"dsl_routing\")."),
            key(
                "route_template",
                STR,
                ALWAYS,
                "Raw route path from the DSL call.",
            ),
            key(
                "normalized_route_template",
                STR,
                ALWAYS,
                "Cross-family normalized route template.",
            ),
            key(
                "dynamic_segments",
                ARR,
                OPT,
                "Route parameter names discovered in the normalized template.",
            ),
            key("scope_path", STR, OPT, "Enclosing namespace/scope path."),
            key(
                "effective_route_template",
                STR,
                OPT,
                "Scope path joined with route template.",
            ),
            key(
                "verb",
                STR,
                OPT,
                "Uppercase HTTP method when verb-restricted.",
            ),
            key("verb_source", STR, OPT, "How the verb was attested."),
            key(
                "controller_action",
                STR,
                OPT,
                "Literal controller#action target.",
            ),
            key("route_name", STR, OPT, "Literal/as-symbol route name."),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "rails.resource_route.v1",
        languages: &["ruby"],
        query_family: "framework",
        description: "A Rails resources/resource declaration.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key("api_style", STR, ALWAYS, "Routing style (\"dsl_routing\")."),
            key("resource_name", STR, ALWAYS, "Declared resource name."),
            key("resource_kind", STR, ALWAYS, "collection or singular."),
            key("only", ARR, OPT, "Literal only: action list."),
            key("except", ARR, OPT, "Literal except: action list."),
            key("scope_path", STR, OPT, "Enclosing namespace/scope path."),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "rails.mount.v1",
        languages: &["ruby"],
        query_family: "framework",
        description: "A Rails mount route for a Rack app or engine.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key("mount_path", STR, ALWAYS, "Raw mount path literal."),
            key(
                "normalized_mount_path",
                STR,
                ALWAYS,
                "Normalized mount path including same-file scope.",
            ),
            key(
                "mount_target",
                STR,
                ALWAYS,
                "Source text of mounted app/engine.",
            ),
            key("scope_path", STR, OPT, "Enclosing namespace/scope path."),
        ],
    },
];
