//! Spring, JVM, and Go net/http-family framework route SPECS.
//!
//! Authored metadata for [`super::super::StructuralFactPatternSpec`] entries.
//! Public registry access remains through
//! [`super::super::structural_fact_pattern_specs`].

use super::super::{
    ALWAYS, ARR, K_FRAMEWORK, K_PATTERN_VERSION, K_QUERY_FAMILY, OPT, STR,
    StructuralFactPatternSpec, key,
};

pub(super) const SPECS: &[StructuralFactPatternSpec] = &[
    StructuralFactPatternSpec {
        pattern_id: "spring.request_mapping.v1",
        languages: &["java", "kotlin"],
        query_family: "framework",
        description: "A Spring MVC request-mapping annotation on a class or method.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key(
                "api_style",
                STR,
                ALWAYS,
                "Routing style (\"annotation_routing\").",
            ),
            key(
                "attribute_kind",
                STR,
                ALWAYS,
                "class_route/http_method/request_mapping shape.",
            ),
            key("route_template", STR, ALWAYS, "Raw static route template."),
            key(
                "normalized_route_template",
                STR,
                ALWAYS,
                "Cross-family normalized route template.",
            ),
            key(
                "dynamic_segments",
                ARR,
                OPT,
                "Route parameter names discovered in the normalized template.",
            ),
            key(
                "class_route_template",
                STR,
                OPT,
                "Nearest class-level route template.",
            ),
            key(
                "effective_route_template",
                STR,
                OPT,
                "Class and method templates joined.",
            ),
            key(
                "verb",
                STR,
                OPT,
                "Uppercase HTTP method when verb-restricted.",
            ),
            key("verb_source", STR, OPT, "How the verb was attested."),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "spring.functional_route.v1",
        languages: &["kotlin"],
        query_family: "framework",
        description: "A Spring functional route: a verb call such as `GET(\"/x\", handler::get)` inside a `coRouter { }` or `router { }` DSL.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key(
                "api_style",
                STR,
                ALWAYS,
                "Routing style (\"functional_routing\").",
            ),
            key(
                "router",
                STR,
                ALWAYS,
                "The DSL builder that holds the route: coRouter or router.",
            ),
            key(
                "route_template",
                STR,
                ALWAYS,
                "Raw static route template of the verb call.",
            ),
            key(
                "normalized_route_template",
                STR,
                ALWAYS,
                "Cross-family normalized route template.",
            ),
            key(
                "dynamic_segments",
                ARR,
                OPT,
                "Route parameter names discovered in the normalized template.",
            ),
            key(
                "nest_route_template",
                STR,
                OPT,
                "The joined static prefixes of the enclosing `nest { }` blocks.",
            ),
            key(
                "effective_route_template",
                STR,
                OPT,
                "Nest prefix and route template joined.",
            ),
            key(
                "verb",
                STR,
                ALWAYS,
                "Uppercase HTTP method of the verb call.",
            ),
            key("verb_source", STR, ALWAYS, "How the verb was attested."),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "akka_http.route.v1",
        languages: &["scala"],
        query_family: "framework",
        description: "An Akka HTTP or Apache Pekko HTTP method directive (`get { }`) inside static `path`/`pathPrefix` directives.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key(
                "api_style",
                STR,
                ALWAYS,
                "Routing style (\"directive_routing\").",
            ),
            key(
                "route_template",
                STR,
                ALWAYS,
                "The joined static path directives around the method directive; a path matcher such as `LongNumber` is a `{LongNumber}` segment.",
            ),
            key(
                "normalized_route_template",
                STR,
                ALWAYS,
                "Cross-family normalized route template.",
            ),
            key(
                "dynamic_segments",
                ARR,
                OPT,
                "Route parameter names discovered in the normalized template.",
            ),
            key("verb", STR, ALWAYS, "Uppercase HTTP method of the route."),
            key("verb_source", STR, ALWAYS, "How the verb was attested."),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "http4s.route.v1",
        languages: &["scala"],
        query_family: "framework",
        description: "An http4s route pattern such as `case GET -> Root / \"users\" / id =>`.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key(
                "api_style",
                STR,
                ALWAYS,
                "Routing style (\"pattern_routing\").",
            ),
            key(
                "route_template",
                STR,
                ALWAYS,
                "The static path of the pattern; a bound name or extractor argument is a `{name}` segment.",
            ),
            key(
                "normalized_route_template",
                STR,
                ALWAYS,
                "Cross-family normalized route template.",
            ),
            key(
                "dynamic_segments",
                ARR,
                OPT,
                "Route parameter names discovered in the normalized template.",
            ),
            key("verb", STR, ALWAYS, "Uppercase HTTP method of the route."),
            key("verb_source", STR, ALWAYS, "How the verb was attested."),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "jaxrs.route.v1",
        languages: &["java"],
        query_family: "framework",
        description: "A JAX-RS / Jakarta REST `@Path` resource class, resource method (`@GET`, `@POST`, …) or sub-resource locator.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key(
                "api_style",
                STR,
                ALWAYS,
                "Routing style (\"annotation_routing\").",
            ),
            key(
                "attribute_kind",
                STR,
                ALWAYS,
                "class_route, resource_method or subresource_locator.",
            ),
            key(
                "route_template",
                STR,
                ALWAYS,
                "Raw static `@Path` template; empty for a resource method without `@Path`.",
            ),
            key(
                "normalized_route_template",
                STR,
                ALWAYS,
                "Cross-family normalized route template.",
            ),
            key(
                "dynamic_segments",
                ARR,
                OPT,
                "Route parameter names discovered in the normalized template.",
            ),
            key(
                "class_route_template",
                STR,
                OPT,
                "The resource class `@Path` template.",
            ),
            key(
                "effective_route_template",
                STR,
                OPT,
                "Class and method templates joined.",
            ),
            key(
                "verb",
                STR,
                OPT,
                "Uppercase HTTP method of a resource method; absent on a class route or sub-resource locator.",
            ),
            key("verb_source", STR, OPT, "How the verb was attested."),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "go.net_http.route.v1",
        languages: &["go"],
        query_family: "framework",
        description: "A Go net/http Handle or HandleFunc route registration.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key("api_style", STR, ALWAYS, "Routing style (\"mux_routing\")."),
            key(
                "route_template",
                STR,
                ALWAYS,
                "Route path portion of the pattern.",
            ),
            key(
                "normalized_route_template",
                STR,
                ALWAYS,
                "Cross-family normalized route template.",
            ),
            key(
                "dynamic_segments",
                ARR,
                OPT,
                "Route parameter names discovered in the normalized template.",
            ),
            key(
                "host",
                STR,
                OPT,
                "Host portion when the Go 1.22+ pattern is host-scoped.",
            ),
            key(
                "verb",
                STR,
                OPT,
                "Method prefix when the Go pattern names one.",
            ),
            key("verb_source", STR, OPT, "How the verb was attested."),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "gin.route.v1",
        languages: &["go"],
        query_family: "framework",
        description: "A gin route registration on a traced router or group receiver.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key(
                "api_style",
                STR,
                ALWAYS,
                "Routing style (\"call_routing\").",
            ),
            key("route_template", STR, ALWAYS, "Raw static route path."),
            key(
                "normalized_route_template",
                STR,
                ALWAYS,
                "Cross-family normalized route template.",
            ),
            key(
                "dynamic_segments",
                ARR,
                OPT,
                "Route parameter names discovered in the normalized template.",
            ),
            key("route_group_prefix", STR, OPT, "Same-file group prefix."),
            key(
                "effective_route_template",
                STR,
                OPT,
                "Group prefix joined with route template.",
            ),
            key("verb", STR, OPT, "Uppercase HTTP method."),
            key("verb_source", STR, OPT, "How the verb was attested."),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "echo.route.v1",
        languages: &["go"],
        query_family: "framework",
        description: "An echo route registration on a traced Echo or group receiver.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key(
                "api_style",
                STR,
                ALWAYS,
                "Routing style (\"call_routing\").",
            ),
            key("route_template", STR, ALWAYS, "Raw static route path."),
            key(
                "normalized_route_template",
                STR,
                ALWAYS,
                "Cross-family normalized route template.",
            ),
            key(
                "dynamic_segments",
                ARR,
                OPT,
                "Route parameter names discovered in the normalized template.",
            ),
            key("route_group_prefix", STR, OPT, "Same-file group prefix."),
            key(
                "effective_route_template",
                STR,
                OPT,
                "Group prefix joined with route template.",
            ),
            key("verb", STR, OPT, "Uppercase HTTP method."),
            key("verb_source", STR, OPT, "How the verb was attested."),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "chi.route.v1",
        languages: &["go"],
        query_family: "framework",
        description: "A go-chi route registration on a traced router, with the same-file `Route` prefix.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key(
                "api_style",
                STR,
                ALWAYS,
                "Routing style (\"call_routing\").",
            ),
            key("route_template", STR, ALWAYS, "Raw static route path."),
            key(
                "normalized_route_template",
                STR,
                ALWAYS,
                "Cross-family normalized route template; `{id}` captures normalize to `:id`.",
            ),
            key(
                "dynamic_segments",
                ARR,
                OPT,
                "Route parameter names discovered in the normalized template.",
            ),
            key("route_group_prefix", STR, OPT, "Same-file router prefix."),
            key(
                "effective_route_template",
                STR,
                OPT,
                "Router prefix joined with route template.",
            ),
            key(
                "verb",
                STR,
                OPT,
                "Uppercase HTTP method; omitted for any-method registrations.",
            ),
            key("verb_source", STR, OPT, "How the verb was attested."),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "chi.mount.v1",
        languages: &["go"],
        query_family: "framework",
        description: "A go-chi `r.Mount(\"/lit\", handler)` sub-router mount at its registration site.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key(
                "mount_path",
                STR,
                ALWAYS,
                "Static mount path, joined with the same-file router prefix.",
            ),
            key(
                "normalized_mount_path",
                STR,
                ALWAYS,
                "Normalized mount path (`{id}` captures as `:id`).",
            ),
            key(
                "mount_target",
                STR,
                OPT,
                "Source text of the mounted handler (no route join is guessed).",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "gorilla_mux.route.v1",
        languages: &["go"],
        query_family: "framework",
        description: "A gorilla/mux `HandleFunc`/`Handle` registration, one fact per `.Methods(...)` verb, with the same-file `PathPrefix(..).Subrouter()` prefix.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key(
                "api_style",
                STR,
                ALWAYS,
                "Routing style (\"call_routing\").",
            ),
            key("route_template", STR, ALWAYS, "Raw static route path."),
            key(
                "normalized_route_template",
                STR,
                ALWAYS,
                "Cross-family normalized route template; `{id}` captures normalize to `:id`.",
            ),
            key(
                "dynamic_segments",
                ARR,
                OPT,
                "Route parameter names discovered in the normalized template.",
            ),
            key("route_group_prefix", STR, OPT, "Same-file router prefix."),
            key(
                "effective_route_template",
                STR,
                OPT,
                "Router prefix joined with route template.",
            ),
            key(
                "verb",
                STR,
                OPT,
                "Uppercase HTTP method; omitted for any-method registrations.",
            ),
            key("verb_source", STR, OPT, "How the verb was attested."),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "fiber.route.v1",
        languages: &["go"],
        query_family: "framework",
        description: "A gofiber route registration on a traced app or `Group` receiver.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key(
                "api_style",
                STR,
                ALWAYS,
                "Routing style (\"call_routing\").",
            ),
            key("route_template", STR, ALWAYS, "Raw static route path."),
            key(
                "normalized_route_template",
                STR,
                ALWAYS,
                "Cross-family normalized route template; `:id` params stay `:id`.",
            ),
            key(
                "dynamic_segments",
                ARR,
                OPT,
                "Route parameter names discovered in the normalized template.",
            ),
            key("route_group_prefix", STR, OPT, "Same-file router prefix."),
            key(
                "effective_route_template",
                STR,
                OPT,
                "Router prefix joined with route template.",
            ),
            key(
                "verb",
                STR,
                OPT,
                "Uppercase HTTP method; omitted for any-method registrations.",
            ),
            key("verb_source", STR, OPT, "How the verb was attested."),
        ],
    },
];
