//! Python (FastAPI/Flask/Django) framework route SPECS.
//!
//! Authored metadata for [`super::super::StructuralFactPatternSpec`] entries.
//! Public registry access remains through
//! [`super::super::structural_fact_pattern_specs`].

use super::super::{
    ALWAYS, ARR, BOOL, K_FRAMEWORK, K_PATTERN_VERSION, K_QUERY_FAMILY, OPT, STR,
    StructuralFactPatternSpec, key,
};

pub(super) const SPECS: &[StructuralFactPatternSpec] = &[
    StructuralFactPatternSpec {
        pattern_id: "fastapi.route.v1",
        languages: &["python"],
        query_family: "framework",
        description: "A static FastAPI path-operation decorator on a traced FastAPI/APIRouter receiver.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key(
                "api_style",
                STR,
                ALWAYS,
                "Routing style (\"decorator_routing\").",
            ),
            key(
                "route_template",
                STR,
                ALWAYS,
                "Raw static route path from the decorator.",
            ),
            key(
                "normalized_route_template",
                STR,
                ALWAYS,
                "Cross-family normalized route template.",
            ),
            key(
                "dynamic_segments",
                ARR,
                OPT,
                "Route parameter names discovered in the normalized template.",
            ),
            key("verb", STR, ALWAYS, "Uppercase HTTP method."),
            key("verb_source", STR, ALWAYS, "How the verb was attested."),
            key("router_prefix", STR, OPT, "Same-file APIRouter prefix."),
            key(
                "effective_route_template",
                STR,
                OPT,
                "Router prefix joined with route template.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "fastapi.include_router.v1",
        languages: &["python"],
        query_family: "framework",
        description: "A FastAPI include_router mount call.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key(
                "mount_target",
                STR,
                ALWAYS,
                "Source text of the included router argument.",
            ),
            key(
                "mount_path",
                STR,
                OPT,
                "Literal prefix mount path, when present.",
            ),
            key(
                "normalized_mount_path",
                STR,
                OPT,
                "Normalized mount path, when a literal prefix is present.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "flask.route.v1",
        languages: &["python"],
        query_family: "framework",
        description: "A static Flask route: a route decorator or an add_url_rule call on a Flask app or Blueprint receiver that is constructed in the file or imported into a file that imports flask.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key(
                "api_style",
                STR,
                ALWAYS,
                "Routing style (\"decorator_routing\" or \"call_routing\" for add_url_rule).",
            ),
            key(
                "route_template",
                STR,
                ALWAYS,
                "Raw static route path from the decorator or add_url_rule call.",
            ),
            key(
                "normalized_route_template",
                STR,
                ALWAYS,
                "Cross-family normalized route template.",
            ),
            key(
                "dynamic_segments",
                ARR,
                OPT,
                "Route parameter names discovered in the normalized template.",
            ),
            key("verb", STR, ALWAYS, "Uppercase HTTP method."),
            key(
                "verb_source",
                STR,
                ALWAYS,
                "Default or attested verb source.",
            ),
            key(
                "blueprint",
                STR,
                OPT,
                "Blueprint name literal for blueprint-owned routes.",
            ),
            key("url_prefix", STR, OPT, "Same-file Blueprint url_prefix."),
            key(
                "view_target",
                STR,
                OPT,
                "Source text of the add_url_rule view function.",
            ),
            key(
                "effective_route_template",
                STR,
                OPT,
                "Blueprint prefix joined with route template.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "flask.blueprint_registration.v1",
        languages: &["python"],
        query_family: "framework",
        description: "A Flask register_blueprint mount call.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key(
                "mount_target",
                STR,
                ALWAYS,
                "Source text of the blueprint argument.",
            ),
            key(
                "mount_path",
                STR,
                OPT,
                "Literal url_prefix mount path, when present.",
            ),
            key(
                "normalized_mount_path",
                STR,
                OPT,
                "Normalized mount path, when a literal url_prefix is present.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "django.url_pattern.v1",
        languages: &["python"],
        query_family: "framework",
        description: "A Django path/re_path URL pattern with a static route argument.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key("api_style", STR, ALWAYS, "Routing style (\"dsl_routing\")."),
            key("route_template", STR, ALWAYS, "Raw static route string."),
            key("route_syntax", STR, ALWAYS, "\"path\" or \"regex\"."),
            key(
                "normalized_route_template",
                STR,
                OPT,
                "Normalized route template for path syntax.",
            ),
            key(
                "dynamic_segments",
                ARR,
                OPT,
                "Route parameter names discovered in path syntax.",
            ),
            key("route_name", STR, OPT, "Literal name= value."),
            key(
                "view_target",
                STR,
                ALWAYS,
                "Source text of the view argument.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "django.url_include.v1",
        languages: &["python"],
        query_family: "framework",
        description: "A Django include mount inside a path() URL pattern.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key("mount_path", STR, ALWAYS, "Raw path() prefix string."),
            key(
                "normalized_mount_path",
                STR,
                ALWAYS,
                "Normalized mount path.",
            ),
            key(
                "included_module",
                STR,
                ALWAYS,
                "Included module literal or source text.",
            ),
            key("namespace", STR, OPT, "Literal namespace= value."),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "drf.router_registration.v1",
        languages: &["python"],
        query_family: "framework",
        description: "A Django REST Framework router.register(prefix, ViewSet) on a same-file DefaultRouter or SimpleRouter.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key(
                "api_style",
                STR,
                ALWAYS,
                "Routing style (\"resource_routing\").",
            ),
            key(
                "resource_name",
                STR,
                ALWAYS,
                "Literal URL prefix the viewset is registered under.",
            ),
            key(
                "viewset",
                STR,
                ALWAYS,
                "Source text of the viewset argument.",
            ),
            key("router", STR, ALWAYS, "Local name of the router receiver."),
            key("basename", STR, OPT, "Literal basename= value."),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "drf.viewset_action.v1",
        languages: &["python"],
        query_family: "framework",
        description: "A Django REST Framework @action extra route on a viewset method.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key(
                "api_style",
                STR,
                ALWAYS,
                "Routing style (\"viewset_action\").",
            ),
            key(
                "verbs",
                ARR,
                ALWAYS,
                "Uppercase HTTP methods from methods= (GET when absent).",
            ),
            key(
                "detail",
                BOOL,
                ALWAYS,
                "True when the route is on one object (detail=True).",
            ),
            key(
                "url_path",
                STR,
                ALWAYS,
                "Literal url_path= value, else the method name.",
            ),
            key("url_name", STR, OPT, "Literal url_name= value."),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "drf.api_view.v1",
        languages: &["python"],
        query_family: "framework",
        description: "A Django REST Framework @api_view function view with its allowed HTTP methods.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            K_FRAMEWORK,
            key("api_style", STR, ALWAYS, "Routing style (\"api_view\")."),
            key(
                "verbs",
                ARR,
                ALWAYS,
                "Uppercase HTTP methods from the decorator (GET when absent).",
            ),
        ],
    },
];
