/// Common R functions that use dots in their names but are NOT S3 methods.
/// These should be classified as plain functions, not method dispatches.
/// Only includes dot-containing names (non-dot names are already excluded by classify_s3).
pub(super) const NON_S3_DOT_FUNCTIONS: &[&str] = &[
    // Data structures
    "data.frame",
    "data.table",
    // I/O
    "read.csv",
    "read.table",
    "read.delim",
    "read.fwf",
    "write.csv",
    "write.table",
    // Type checking (is.*)
    "is.na",
    "is.null",
    "is.numeric",
    "is.character",
    "is.logical",
    "is.integer",
    "is.double",
    "is.complex",
    "is.list",
    "is.vector",
    "is.matrix",
    "is.array",
    "is.factor",
    "is.ordered",
    "is.data.frame",
    "is.function",
    "is.environment",
    "is.recursive",
    "is.atomic",
    "is.finite",
    "is.infinite",
    "is.nan",
    "is.element",
    "is.loaded",
    "is.pairlist",
    "is.primitive",
    "is.R",
    // Type coercion (as.*)
    "as.character",
    "as.numeric",
    "as.integer",
    "as.double",
    "as.logical",
    "as.complex",
    "as.factor",
    "as.data.frame",
    "as.matrix",
    "as.list",
    "as.vector",
    "as.Date",
    "as.POSIXct",
    "as.POSIXlt",
    // System/control
    "on.exit",
    "do.call",
    "set.seed",
    // System info (sys.*, Sys.*)
    "sys.call",
    "sys.function",
    "sys.frame",
    "sys.nframe",
    "sys.on.exit",
    "sys.parents",
    "sys.status",
    "Sys.time",
    "Sys.Date",
    "Sys.sleep",
    "Sys.getenv",
    "Sys.setenv",
    "Sys.timezone",
    "Sys.glob",
    // File system
    "file.path",
    "file.exists",
    "file.create",
    "file.remove",
    "file.rename",
    "file.copy",
    "file.info",
    "file.size",
    "file.access",
    "file.choose",
    "file.show",
    "dir.create",
    "dir.exists",
    "list.files",
    "list.dirs",
    // Timing
    "proc.time",
    "system.time",
    "system.file",
    // Environment/scope
    "parent.frame",
    "parent.env",
    "new.env",
    // Utility
    "all.equal",
    "all.names",
    "all.vars",
    "which.min",
    "which.max",
    "seq.int",
    "seq.along",
    "make.names",
    "make.unique",
    "attr.all.equal",
    "match.arg",
    "match.call",
    "match.fun",
    // Modeling
    "model.frame",
    "model.matrix",
    "model.response",
    "drop.terms",
    // Misc
    "base.url",
    "try.catch",
    "with.default",
    "within.data.frame",
    "within.list",
    "body.function",
    "close.connection",
    "open.connection",
];
