//! Structural-fact pattern SPECS for the `sql` registry family.
//!
//! Authored metadata for [`super::StructuralFactPatternSpec`] entries. Public
//! registry access remains through [`super::structural_fact_pattern_specs`].

use super::{
    ALWAYS, ARR, BOOL, K_PATTERN_VERSION, K_QUERY_FAMILY, NUM, OPT, STR, StructuralFactPatternSpec,
    key,
};

pub(super) const SPECS: &[StructuralFactPatternSpec] = &[
    // -----------------------------------------------------------------------
    // SQL collector (base/sql_structural_facts.rs).
    // -----------------------------------------------------------------------
    StructuralFactPatternSpec {
        pattern_id: "sql.table_definition.v1",
        languages: &["sql"],
        query_family: "schema_structure",
        description: "A SQL `CREATE TABLE` definition.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key(
                "table_name",
                STR,
                ALWAYS,
                "Name of the table being created.",
            ),
            key(
                "schema_name",
                STR,
                OPT,
                "Schema/namespace qualifier when the table name is qualified.",
            ),
            key(
                "column_count",
                NUM,
                ALWAYS,
                "Count of column definitions in the table body.",
            ),
            key(
                "constraint_count",
                NUM,
                ALWAYS,
                "Count of table-level constraints in the table body.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "sql.view_definition.v1",
        languages: &["sql"],
        query_family: "schema_structure",
        description: "A SQL `CREATE VIEW` definition.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key("view_name", STR, ALWAYS, "Name of the view being created."),
            key(
                "schema_name",
                STR,
                OPT,
                "Schema/namespace qualifier when the view name is qualified.",
            ),
            key(
                "source_table_count",
                NUM,
                ALWAYS,
                "Number of distinct source tables in the view query.",
            ),
            key(
                "source_tables",
                ARR,
                ALWAYS,
                "Sorted, deduped list of source table names (may be empty).",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "sql.trigger_definition.v1",
        languages: &["sql"],
        query_family: "schema_structure",
        description: "A SQL `CREATE TRIGGER` definition.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key("trigger_name", STR, ALWAYS, "Name of the trigger."),
            key(
                "schema_name",
                STR,
                OPT,
                "Schema qualifier for the trigger (normal parse path only).",
            ),
            key(
                "timing",
                STR,
                OPT,
                "Trigger timing (before/after) when detected.",
            ),
            key(
                "event",
                STR,
                OPT,
                "Trigger event (insert/update/delete/truncate) when detected.",
            ),
            key(
                "target_table",
                STR,
                OPT,
                "Table the trigger fires on when resolvable.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "sql.index_definition.v1",
        languages: &["sql"],
        query_family: "schema_structure",
        description: "A SQL `CREATE INDEX` definition.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key("index_name", STR, ALWAYS, "Name of the index."),
            key(
                "table_name",
                STR,
                OPT,
                "Table the index is defined on when resolvable.",
            ),
            key(
                "unique",
                BOOL,
                ALWAYS,
                "Whether the index carries the UNIQUE keyword.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "sql.column_definition.v1",
        languages: &["sql"],
        query_family: "schema_structure",
        description: "A SQL column definition inside a CREATE TABLE.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key("column_name", STR, ALWAYS, "Name of the column."),
            key(
                "type_name",
                STR,
                OPT,
                "Declared column data type when resolvable.",
            ),
            key(
                "table_name",
                STR,
                OPT,
                "Enclosing CREATE TABLE name when an ancestor table is found.",
            ),
            key("nullable", BOOL, ALWAYS, "Whether the column allows NULL."),
            key(
                "has_default",
                BOOL,
                ALWAYS,
                "Whether the column has a DEFAULT clause.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "sql.constraint.v1",
        languages: &["sql"],
        query_family: "schema_structure",
        description: "A SQL table or column constraint.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key(
                "constraint_type",
                STR,
                ALWAYS,
                "Constraint category (primary_key/foreign_key/unique/check/index).",
            ),
            key(
                "constraint_name",
                STR,
                OPT,
                "Explicit constraint name when present.",
            ),
            key(
                "table_name",
                STR,
                OPT,
                "Enclosing CREATE TABLE name when resolvable.",
            ),
            key(
                "column_names",
                ARR,
                OPT,
                "Constrained column names; omitted when empty.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "sql.foreign_key.v1",
        languages: &["sql"],
        query_family: "schema_structure",
        description: "A SQL foreign-key constraint.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key(
                "table_name",
                STR,
                OPT,
                "Local table declaring the foreign key when resolvable.",
            ),
            key(
                "column_names",
                ARR,
                OPT,
                "Local column names participating in the FK; omitted when empty.",
            ),
            key(
                "referenced_table",
                STR,
                ALWAYS,
                "Target table the FK references.",
            ),
            key(
                "referenced_schema",
                STR,
                OPT,
                "Schema qualifier of the referenced table when present.",
            ),
            key(
                "referenced_columns",
                ARR,
                OPT,
                "Referenced column names on the target table; omitted when empty.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "sql.select_query.v1",
        languages: &["sql"],
        query_family: "query_structure",
        description: "A SQL `SELECT` query.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key(
                "projection_count",
                NUM,
                ALWAYS,
                "Number of selected projections/terms.",
            ),
            key(
                "source_count",
                NUM,
                ALWAYS,
                "Number of FROM relations plus joins.",
            ),
            key(
                "has_where",
                BOOL,
                ALWAYS,
                "Whether the query has a WHERE clause.",
            ),
            key(
                "has_group_by",
                BOOL,
                ALWAYS,
                "Whether the query has a GROUP BY clause.",
            ),
            key(
                "has_order_by",
                BOOL,
                ALWAYS,
                "Whether the query has an ORDER BY clause.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "sql.cte.v1",
        languages: &["sql"],
        query_family: "query_structure",
        description: "A SQL common table expression (`WITH`).",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key(
                "cte_name",
                STR,
                ALWAYS,
                "Name of the common table expression.",
            ),
            key(
                "recursive",
                BOOL,
                ALWAYS,
                "Whether the enclosing WITH clause is RECURSIVE.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "sql.join.v1",
        languages: &["sql"],
        query_family: "query_structure",
        description: "A SQL join clause.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key(
                "join_type",
                STR,
                ALWAYS,
                "Join kind (inner/left/right/full/cross); defaults to \"inner\".",
            ),
            key(
                "left_table",
                STR,
                OPT,
                "Left-side table from the enclosing FROM when resolvable.",
            ),
            key(
                "right_table",
                STR,
                OPT,
                "Right-side (joined) table when resolvable.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "sql.transaction.v1",
        languages: &["sql"],
        query_family: "transaction_structure",
        description: "A SQL transaction control statement.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key(
                "transaction_kind",
                STR,
                ALWAYS,
                "Transaction verb (begin/commit/rollback, else \"transaction\").",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "sql.update_statement.v1",
        languages: &["sql"],
        query_family: "mutation_structure",
        description: "A SQL `UPDATE` statement.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key(
                "table_name",
                STR,
                OPT,
                "Target table of the UPDATE when resolvable.",
            ),
            key(
                "has_where",
                BOOL,
                ALWAYS,
                "Whether the UPDATE has a WHERE clause.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "sql.merge_statement.v1",
        languages: &["sql"],
        query_family: "mutation_structure",
        description: "A parser-backed T-SQL `MERGE` statement.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key(
                "target_table",
                STR,
                ALWAYS,
                "Normalized target table of the MERGE.",
            ),
            key(
                "source_kind",
                STR,
                ALWAYS,
                "MERGE source shape: values, query, or table.",
            ),
            key(
                "has_when_matched",
                BOOL,
                ALWAYS,
                "Whether the MERGE has a WHEN MATCHED clause.",
            ),
            key(
                "has_when_not_matched",
                BOOL,
                ALWAYS,
                "Whether the MERGE has a WHEN NOT MATCHED clause.",
            ),
            key(
                "source_table",
                STR,
                OPT,
                "Normalized source table when the parser proves a static table source.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "sql.insert_statement.v1",
        languages: &["sql"],
        query_family: "mutation_structure",
        description: "A SQL `INSERT` statement.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key(
                "table_name",
                STR,
                OPT,
                "Target table of the INSERT when resolvable.",
            ),
            key(
                "has_values",
                BOOL,
                ALWAYS,
                "Whether the INSERT uses a VALUES clause.",
            ),
            key(
                "has_select",
                BOOL,
                ALWAYS,
                "Whether the INSERT sources rows from a SELECT.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "sql.delete_statement.v1",
        languages: &["sql"],
        query_family: "mutation_structure",
        description: "A SQL `DELETE` statement.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key(
                "table_name",
                STR,
                OPT,
                "Target table of the DELETE when resolvable.",
            ),
            key(
                "has_where",
                BOOL,
                ALWAYS,
                "Whether the DELETE has a WHERE clause.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "sql.procedure_definition.v1",
        languages: &["sql"],
        query_family: "schema_structure",
        description: "A SQL stored procedure definition (`CREATE PROCEDURE`).",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key("routine_name", STR, ALWAYS, "Normalized procedure name."),
            key(
                "parameter_count",
                NUM,
                ALWAYS,
                "Number of declared procedure parameters.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "sql.function_definition.v1",
        languages: &["sql"],
        query_family: "schema_structure",
        description: "A SQL function definition (`CREATE FUNCTION`).",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key("routine_name", STR, ALWAYS, "Normalized function name."),
            key(
                "parameter_count",
                NUM,
                ALWAYS,
                "Number of declared function parameters.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "sql.window_definition.v1",
        languages: &["sql"],
        query_family: "query_structure",
        description: "A SQL window clause or window function (`WINDOW` / `OVER`).",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key(
                "window_kind",
                STR,
                ALWAYS,
                "Window shape: \"window_clause\" or \"window_function\".",
            ),
            key(
                "window_name",
                STR,
                OPT,
                "Named window identifier for WINDOW clauses.",
            ),
            key(
                "function_name",
                STR,
                OPT,
                "Window function name for OVER expressions.",
            ),
            key(
                "has_partition_by",
                BOOL,
                ALWAYS,
                "Whether the window specification includes PARTITION BY.",
            ),
            key(
                "has_order_by",
                BOOL,
                ALWAYS,
                "Whether the window specification includes ORDER BY.",
            ),
        ],
    },
];
