//! Tests for julie-extractors
//!
//! All extractor tests organized by language.

pub mod actix;
pub mod annotations;
pub mod api_surface;
pub mod axum;
pub mod base;
pub mod bash;
pub mod body_span;
pub mod c;
#[cfg(feature = "test-capability-matrix")]
pub mod capability_matrix;
pub mod capability_snapshot_test;
pub mod complexity_metrics;
pub mod cpp;
pub mod csharp;
pub mod css;
pub mod dart;
pub mod data_format_relationships;
pub mod doc_comments;
pub mod elixir;
pub mod embedded_spans;
pub mod express;
pub mod fastify;
pub mod gdscript;
pub mod go;
pub mod go_http;
#[cfg(feature = "test-golden")]
pub mod golden;
pub mod helpers;
pub mod html;
pub mod http_client;
pub mod identifier_semantics;
pub mod java;
pub mod javascript;
pub mod json;
pub mod jsonl_invariants;
pub mod jsonl_pipeline;
pub mod kind_conversions;
pub mod kotlin;
pub mod kotlin_spring;
pub mod language_policy;
pub mod laravel;
pub mod lua;
pub mod markdown;
pub mod nestjs;
pub mod nuxt;
#[cfg(feature = "test-certification")]
pub mod parser_upgrade;
pub mod path_identity;
pub mod path_invariants;
#[cfg(feature = "test-capability-matrix")]
pub mod pending_shape_contract;
pub mod php;
pub mod phoenix;
pub mod pipeline;
pub mod powershell;
pub mod python;
pub mod python_web;
pub mod qml;
pub mod r;
pub mod rails_routes;
pub mod razor;
pub mod react;
pub mod regex;
pub mod relationship_precision;
pub mod review_regressions;
pub mod ruby;
pub mod rust;
pub mod scala;
pub mod source_regions;
pub mod spring;
pub mod sql;
pub mod structural_fact_registry;
pub mod structural_facts;
pub mod swift;
pub mod toml;
pub mod type_invariants;
pub mod typescript;
pub mod vbnet;
pub mod vue;
pub mod yaml;
pub mod zig;

// Cross-cutting concerns
pub mod factory_tests;
pub mod test_detection;
pub mod test_tiers;
