//! HTML structural-fact pattern SPECS.
//!
//! Authored metadata for [`super::super::StructuralFactPatternSpec`] entries.
//! Public registry access remains through
//! [`super::super::structural_fact_pattern_specs`].

use super::super::{
    ALWAYS, BOOL, K_PATTERN_VERSION, K_QUERY_FAMILY, NUM, OPT, STR, StructuralFactPatternSpec, key,
};

pub(super) const SPECS: &[StructuralFactPatternSpec] = &[
    StructuralFactPatternSpec {
        pattern_id: "html.link.v1",
        languages: &["html"],
        query_family: "document_navigation",
        description: "An HTML anchor (`<a href>`) link.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key("tag_name", STR, ALWAYS, "The element tag name (\"a\")."),
            key("href", STR, ALWAYS, "Link target from the href attribute."),
            key("id", STR, OPT, "Element id attribute, when present."),
            key("class", STR, OPT, "Element class attribute, when present."),
            key("rel", STR, OPT, "Link rel attribute, when present."),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "html.area_link.v1",
        languages: &["html"],
        query_family: "document_navigation",
        description: "An HTML image-map area link (`<area href>`).",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key("tag_name", STR, ALWAYS, "The element tag name (\"area\")."),
            key("href", STR, ALWAYS, "Link target from the href attribute."),
            key("alt", STR, OPT, "Area alt text, when present."),
            key("shape", STR, OPT, "Area shape attribute, when present."),
            key("coords", STR, OPT, "Area coords attribute, when present."),
            key("id", STR, OPT, "Element id attribute, when present."),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "html.media.v1",
        languages: &["html"],
        query_family: "document_assets",
        description: "An HTML media reference (`<img>`, `<source>`, audio/video/track with src).",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key(
                "tag_name",
                STR,
                ALWAYS,
                "Media element tag name (img/source/audio/video/track).",
            ),
            key(
                "src",
                STR,
                ALWAYS,
                "Media source URL from the src attribute.",
            ),
            key("type", STR, OPT, "MIME type attribute, when present."),
            key("alt", STR, OPT, "Alt text for images, when present."),
            key("id", STR, OPT, "Element id attribute, when present."),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "html.landmark.v1",
        languages: &["html"],
        query_family: "document_landmarks",
        description: "An HTML landmark element or element with a landmark role.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key(
                "tag_name",
                STR,
                ALWAYS,
                "Landmark tag name (header/nav/main/aside/footer or role-bearing element).",
            ),
            key("role", STR, OPT, "ARIA role attribute, when present."),
            key("id", STR, OPT, "Element id attribute, when present."),
            key(
                "aria_label",
                STR,
                OPT,
                "aria-label attribute, when present.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "html.data_attribute.v1",
        languages: &["html"],
        query_family: "document_attributes",
        description: "A generic HTML `data-*` attribute (excluding htmx/Alpine reserved prefixes).",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key("tag_name", STR, ALWAYS, "Owning element tag name."),
            key("attribute_name", STR, ALWAYS, "Full data-* attribute name."),
            key("value", STR, ALWAYS, "Attribute value text."),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "html.script.v1",
        languages: &["html"],
        query_family: "document_assets",
        description: "An HTML `<script>` element.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key(
                "tag_name",
                STR,
                ALWAYS,
                "The element tag name (\"script\").",
            ),
            key(
                "inline",
                BOOL,
                ALWAYS,
                "True when the script has no src (inline body).",
            ),
            key("src", STR, OPT, "External script src, when present."),
            key("type", STR, OPT, "Script type attribute, when present."),
            key("id", STR, OPT, "Element id attribute, when present."),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "html.form.v1",
        languages: &["html"],
        query_family: "document_forms",
        description: "An HTML `<form>` element.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key("tag_name", STR, ALWAYS, "The element tag name (\"form\")."),
            key("action", STR, OPT, "Raw action attribute, when present."),
            key(
                "method",
                STR,
                ALWAYS,
                "Normalized lowercase HTTP method, defaulting to \"get\".",
            ),
            key(
                "method_source",
                STR,
                ALWAYS,
                "Whether method was \"explicit\" on the tag or \"default\".",
            ),
            key(
                "action_kind",
                STR,
                ALWAYS,
                "Action classification (static_path/other/same_document).",
            ),
            key(
                "target_path",
                STR,
                OPT,
                "The action value when it is a static path.",
            ),
            key("id", STR, OPT, "Form id attribute, when present."),
            key("name", STR, OPT, "Form name attribute, when present."),
            key("enctype", STR, OPT, "Form enctype attribute, when present."),
            key("target", STR, OPT, "Form target attribute, when present."),
            key(
                "autocomplete",
                STR,
                OPT,
                "Form autocomplete attribute, when present.",
            ),
            key(
                "novalidate",
                BOOL,
                ALWAYS,
                "True when the novalidate attribute is present.",
            ),
            key(
                "control_count",
                NUM,
                ALWAYS,
                "Number of descendant form controls.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "html.form_control.v1",
        languages: &["html"],
        query_family: "document_forms",
        description: "An HTML form control (input/button/select/textarea).",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key(
                "tag_name",
                STR,
                ALWAYS,
                "Control tag name (input/button/select/textarea).",
            ),
            key("type", STR, OPT, "Control type attribute, when present."),
            key("name", STR, OPT, "Control name attribute, when present."),
            key("id", STR, OPT, "Control id attribute, when present."),
            key("value", STR, OPT, "Control value attribute, when present."),
            key(
                "required",
                BOOL,
                ALWAYS,
                "True when the required attribute is present.",
            ),
            key(
                "disabled",
                BOOL,
                OPT,
                "Present (true) only when the disabled attribute exists.",
            ),
            key(
                "readonly",
                BOOL,
                OPT,
                "Present (true) only when the readonly attribute exists.",
            ),
            key(
                "checked",
                BOOL,
                OPT,
                "Present (true) only when the checked attribute exists.",
            ),
            key(
                "multiple",
                BOOL,
                OPT,
                "Present (true) only when the multiple attribute exists.",
            ),
            key(
                "form_id",
                STR,
                OPT,
                "Owning form's id, when an owner form is resolved.",
            ),
            key(
                "form_name",
                STR,
                OPT,
                "Owning form's name, when an owner form is resolved.",
            ),
            key(
                "form_action",
                STR,
                OPT,
                "Owning form's action, when an owner form is resolved.",
            ),
            key(
                "form_method",
                STR,
                OPT,
                "Owning form's normalized method, when an owner form is resolved.",
            ),
        ],
    },
];
