use super::*;

pub(super) const LANGUAGE_SPECS: &[LanguageSpec] = &[
    spec(
        "rust",
        &["rs"],
        "tree-sitter-rust",
        FULL_CAPABILITIES,
        parser_rust,
        RUST_DOCS,
    ),
    spec(
        "c",
        &["c", "h"],
        "tree-sitter-c",
        FULL_CAPABILITIES,
        parser_c,
        C_DOCS,
    ),
    spec(
        "cpp",
        &["cpp", "cc", "cxx", "c++", "hpp", "hh", "hxx", "h++"],
        "tree-sitter-cpp",
        FULL_CAPABILITIES,
        parser_cpp,
        C_DOCS,
    ),
    spec(
        "go",
        &["go"],
        "tree-sitter-go",
        FULL_CAPABILITIES,
        parser_go,
        GO_DOCS,
    ),
    spec(
        "zig",
        &["zig"],
        "tree-sitter-zig",
        FULL_CAPABILITIES,
        parser_zig,
        ZIG_DOCS,
    ),
    spec(
        "typescript",
        &["ts", "mts", "cts"],
        "tree-sitter-typescript",
        FULL_CAPABILITIES,
        parser_typescript,
        JS_DOCS,
    ),
    spec(
        "tsx",
        &["tsx"],
        "tree-sitter-typescript",
        FULL_CAPABILITIES,
        parser_tsx,
        JS_DOCS,
    ),
    spec(
        "javascript",
        &["js", "mjs", "cjs"],
        "tree-sitter-javascript",
        FULL_CAPABILITIES,
        parser_javascript,
        JS_DOCS,
    ),
    spec(
        "jsx",
        &["jsx"],
        "tree-sitter-javascript",
        FULL_CAPABILITIES,
        parser_javascript,
        JS_DOCS,
    ),
    spec(
        "html",
        &["html", "htm"],
        "tree-sitter-html",
        FULL_CAPABILITIES,
        parser_html,
        HTML_DOCS,
    ),
    spec(
        "css",
        &["css"],
        "tree-sitter-css",
        RELATIONSHIP_DATA_CAPABILITIES,
        parser_css,
        CSS_DOCS,
    ),
    spec(
        "vue",
        &["vue"],
        "tree-sitter-html",
        FULL_CAPABILITIES,
        parser_html,
        HTML_DOCS,
    ),
    spec(
        "python",
        &["py", "pyi", "pyw"],
        "tree-sitter-python",
        FULL_CAPABILITIES,
        parser_python,
        EMPTY,
    ),
    spec(
        "java",
        &["java"],
        "tree-sitter-java",
        FULL_CAPABILITIES,
        parser_java,
        JAVA_DOCS,
    ),
    spec(
        "csharp",
        &["cs"],
        "tree-sitter-c-sharp",
        FULL_CAPABILITIES,
        parser_csharp,
        CSHARP_DOCS,
    ),
    spec(
        "vbnet",
        &["vb"],
        "tree-sitter-vb-dotnet",
        FULL_CAPABILITIES,
        parser_vbnet,
        VBNET_DOCS,
    ),
    spec(
        "php",
        &["php", "phtml"],
        "tree-sitter-php",
        FULL_CAPABILITIES,
        parser_php,
        PHP_DOCS,
    ),
    spec(
        "ruby",
        &["rb", "rbw"],
        "tree-sitter-ruby",
        FULL_CAPABILITIES,
        parser_ruby,
        HASH_DOCS,
    ),
    spec(
        "swift",
        &["swift"],
        "tree-sitter-swift",
        FULL_CAPABILITIES,
        parser_swift,
        SWIFT_DOCS,
    ),
    spec(
        "kotlin",
        &["kt", "kts"],
        "tree-sitter-kotlin-ng",
        FULL_CAPABILITIES,
        parser_kotlin,
        KOTLIN_DOCS,
    ),
    spec(
        "scala",
        &["scala", "sc"],
        "tree-sitter-scala",
        FULL_CAPABILITIES,
        parser_scala,
        EMPTY,
    ),
    spec(
        "dart",
        &["dart"],
        "tree-sitter-dart",
        FULL_CAPABILITIES,
        parser_dart,
        DART_DOCS,
    ),
    spec(
        "elixir",
        &["ex", "exs"],
        "tree-sitter-elixir",
        FULL_CAPABILITIES,
        parser_elixir,
        EMPTY,
    ),
    spec(
        "lua",
        &["lua"],
        "tree-sitter-lua",
        PENDING_NO_TYPES_CAPABILITIES,
        parser_lua,
        LUA_DOCS,
    ),
    spec(
        "qml",
        &["qml"],
        "tree-sitter-qmljs",
        PENDING_NO_TYPES_CAPABILITIES,
        parser_qml,
        EMPTY,
    ),
    spec(
        "r",
        &["r", "R"],
        "tree-sitter-r",
        PENDING_NO_TYPES_CAPABILITIES,
        parser_r,
        R_DOCS,
    ),
    spec(
        "bash",
        &["sh", "bash"],
        "tree-sitter-bash",
        FULL_CAPABILITIES,
        parser_bash,
        HASH_DOCS,
    ),
    spec(
        "powershell",
        &["ps1", "psm1", "psd1"],
        "tree-sitter-powershell",
        FULL_CAPABILITIES,
        parser_powershell,
        EMPTY,
    ),
    spec(
        "gdscript",
        &["gd"],
        "tree-sitter-gdscript",
        FULL_CAPABILITIES,
        parser_gdscript,
        GDSCRIPT_DOCS,
    ),
    spec(
        "razor",
        &["razor", "cshtml"],
        "tree-sitter-razor",
        NO_PENDING_CAPABILITIES,
        parser_razor,
        RAZOR_DOCS,
    ),
    spec(
        "sql",
        &["sql"],
        "tree-sitter-sequel",
        FULL_CAPABILITIES,
        parser_sql,
        SQL_DOCS,
    ),
    spec(
        "regex",
        &["regex"],
        "tree-sitter-regex",
        NO_PENDING_CAPABILITIES,
        parser_regex,
        EMPTY,
    ),
    spec(
        "markdown",
        &["md", "markdown"],
        "tree-sitter-md",
        RELATIONSHIP_DATA_NO_IDENTIFIERS_CAPABILITIES,
        parser_markdown,
        EMPTY,
    ),
    spec(
        "json",
        &["json", "jsonl", "jsonc"],
        "tree-sitter-json",
        PENDING_NO_TYPES_NO_IDENTIFIERS_CAPABILITIES,
        parser_json,
        EMPTY,
    ),
    spec(
        "toml",
        &["toml"],
        "tree-sitter-toml-ng",
        RELATIONSHIP_DATA_NO_IDENTIFIERS_CAPABILITIES,
        parser_toml,
        EMPTY,
    ),
    spec(
        "yaml",
        &["yml", "yaml"],
        "tree-sitter-yaml",
        RELATIONSHIP_DATA_CAPABILITIES,
        parser_yaml,
        EMPTY,
    ),
];

const fn spec(
    name: &'static str,
    extensions: &'static [&'static str],
    parser_crate: &'static str,
    capabilities: LanguageCapabilities,
    parser: ParserFn,
    doc_comment_styles: &'static [DocCommentStyle],
) -> LanguageSpec {
    LanguageSpec {
        name,
        aliases: &[],
        extensions,
        parser_crate,
        capabilities,
        parser,
        doc_comment_styles,
    }
}
