//! Built-in language-local SPECS for QML, qmldir, and the QML JavaScript directive.

use super::super::{
    ALWAYS, BOOL, K_PATTERN_VERSION, K_QUERY_FAMILY, OPT, STR, StructuralFactPatternSpec, key,
};

pub(super) const SPECS: &[StructuralFactPatternSpec] = &[
    StructuralFactPatternSpec {
        pattern_id: "qml.import_statement.v1",
        languages: &["qml"],
        query_family: "imports",
        description: "A QML `import` statement.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key(
                "import_module",
                STR,
                ALWAYS,
                "The normalized imported QML module or resource source.",
            ),
            key(
                "source",
                STR,
                ALWAYS,
                "The normalized imported QML module or resource source.",
            ),
            key(
                "source_kind",
                STR,
                ALWAYS,
                "Whether the parser source is a QML URI or quoted resource path.",
            ),
            key(
                "import_kind",
                STR,
                ALWAYS,
                "The policy classification of a module, directory, or JavaScript import.",
            ),
            key(
                "version",
                STR,
                OPT,
                "The imported QML module version, when present.",
            ),
            key(
                "alias",
                STR,
                OPT,
                "The import namespace alias, when present.",
            ),
            key(
                "local_name",
                STR,
                OPT,
                "The local namespace name introduced by an aliased import.",
            ),
            key(
                "imported_name",
                STR,
                OPT,
                "The imported source name used by an aliased import.",
            ),
            key(
                "is_namespace",
                BOOL,
                OPT,
                "Whether the import introduces a namespace alias.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "qml.pragma.v1",
        languages: &["qml"],
        query_family: "pragmas",
        description: "A QML `pragma` directive.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key("name", STR, ALWAYS, "The pragma name."),
            key(
                "value",
                STR,
                OPT,
                "The pragma value, when the pragma has one.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "qml.property_declaration.v1",
        languages: &["qml"],
        query_family: "properties",
        description: "A QML `property` declaration.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key("property_name", STR, OPT, "The declared property name."),
            key("property_type", STR, OPT, "The declared property type."),
            key(
                "required",
                BOOL,
                OPT,
                "True for a `required property`; absent otherwise.",
            ),
            key(
                "readonly",
                BOOL,
                OPT,
                "True for a `readonly property`; absent otherwise.",
            ),
            key(
                "default",
                BOOL,
                OPT,
                "True for a `default property`; absent otherwise.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "qml.signal_declaration.v1",
        languages: &["qml"],
        query_family: "signals",
        description: "A QML `signal` declaration.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key("signal_name", STR, OPT, "The declared signal name."),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "qml.binding.v1",
        languages: &["qml"],
        query_family: "bindings",
        description: "A QML property binding.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key(
                "property_name",
                STR,
                ALWAYS,
                "The bound property's name, qualified by any grouped property blocks around it (`font.bold`).",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "qml.object_instantiation.v1",
        languages: &["qml"],
        query_family: "objects",
        description: "A QML object-definition use with its declared component type.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key(
                "type_name",
                STR,
                ALWAYS,
                "The instantiated QML component type.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "qml.component_url.v1",
        languages: &["qml"],
        query_family: "objects",
        description: "A string literal naming a `.qml` component file, passed to a call (`Qt.resolvedUrl`, `Qt.createComponent`, `push`) or bound directly to a property (`source`, `initialItem`).",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key("url", STR, ALWAYS, "The component URL text."),
            key(
                "carrier",
                STR,
                ALWAYS,
                "The callee the URL is an argument of, or the property it is bound to.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "qml.typeinfo_declaration.v1",
        languages: &["qml"],
        query_family: "typeinfo",
        description: "A declaration in a generated QML type-information file.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key(
                "type_name",
                STR,
                ALWAYS,
                "The qmltypes declaration node type.",
            ),
            key(
                "typeinfo_kind",
                STR,
                ALWAYS,
                "The normalized qmltypes declaration role.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "javascript.qml_directive.v1",
        languages: &["javascript"],
        query_family: "directives",
        description: "A Qt QML `.pragma` or `.import` directive at the top of a JavaScript file.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key("directive", STR, ALWAYS, "The directive form (`pragma`)."),
            key("name", STR, ALWAYS, "The pragma name."),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "qmldir.module.v1",
        languages: &["qmldir"],
        query_family: "qmldir",
        description: "A QML module declaration from a qmldir manifest.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key("directive", STR, ALWAYS, "The manifest directive name."),
            key("module", STR, ALWAYS, "The declared QML module name."),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "qmldir.object_type.v1",
        languages: &["qmldir"],
        query_family: "qmldir",
        description: "A public QML object type declared by a qmldir manifest.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key("directive", STR, ALWAYS, "The manifest directive name."),
            key("type_name", STR, ALWAYS, "The declared QML object type."),
            key("version", STR, ALWAYS, "The declared QML type version."),
            key("file", STR, ALWAYS, "The QML source file backing the type."),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "qmldir.singleton_type.v1",
        languages: &["qmldir"],
        query_family: "qmldir",
        description: "A singleton QML type declared by a qmldir manifest.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key("directive", STR, ALWAYS, "The manifest directive name."),
            key("type_name", STR, ALWAYS, "The declared singleton type."),
            key("version", STR, ALWAYS, "The declared singleton version."),
            key(
                "file",
                STR,
                ALWAYS,
                "The QML source file backing the singleton.",
            ),
            key(
                "singleton",
                BOOL,
                ALWAYS,
                "Whether the declared type is a singleton.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "qmldir.internal_type.v1",
        languages: &["qmldir"],
        query_family: "qmldir",
        description: "An internal QML type declared by a qmldir manifest.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key("directive", STR, ALWAYS, "The manifest directive name."),
            key("type_name", STR, ALWAYS, "The declared internal type."),
            key("file", STR, ALWAYS, "The QML source file backing the type."),
            key(
                "internal",
                BOOL,
                ALWAYS,
                "Whether the declared type is internal.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "qmldir.javascript_resource.v1",
        languages: &["qmldir"],
        query_family: "qmldir",
        description: "A JavaScript resource declared by a qmldir manifest.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key("directive", STR, ALWAYS, "The manifest directive name."),
            key(
                "resource_name",
                STR,
                ALWAYS,
                "The resource's manifest name.",
            ),
            key("version", STR, ALWAYS, "The declared resource version."),
            key("file", STR, ALWAYS, "The JavaScript resource file."),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "qmldir.plugin.v1",
        languages: &["qmldir"],
        query_family: "qmldir",
        description: "A native plugin declaration from a qmldir manifest.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key("directive", STR, ALWAYS, "The manifest directive name."),
            key("name", STR, ALWAYS, "The plugin name."),
            key("optional", BOOL, ALWAYS, "Whether the plugin is optional."),
            key("path", STR, OPT, "The optional plugin library path."),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "qmldir.classname.v1",
        languages: &["qmldir"],
        query_family: "qmldir",
        description: "A C++ classname declaration from a qmldir manifest.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key("directive", STR, ALWAYS, "The manifest directive name."),
            key("class_name", STR, ALWAYS, "The native class name."),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "qmldir.typeinfo.v1",
        languages: &["qmldir"],
        query_family: "qmldir",
        description: "A generated QML type-information file declaration.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key("directive", STR, ALWAYS, "The manifest directive name."),
            key("file", STR, ALWAYS, "The qmltypes file name."),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "qmldir.depends.v1",
        languages: &["qmldir"],
        query_family: "qmldir",
        description: "A module dependency declaration from a qmldir manifest.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key("directive", STR, ALWAYS, "The manifest directive name."),
            key("module", STR, ALWAYS, "The dependent module name."),
            key("version", STR, OPT, "The optional dependency version."),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "qmldir.import.v1",
        languages: &["qmldir"],
        query_family: "qmldir",
        description: "An additional module import declaration from a qmldir manifest.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key("directive", STR, ALWAYS, "The manifest directive name."),
            key("module", STR, ALWAYS, "The imported module name."),
            key("version", STR, OPT, "The optional import version."),
            key("optional", BOOL, ALWAYS, "Whether the import is optional."),
            key(
                "default",
                BOOL,
                ALWAYS,
                "Whether the import is the default tooling import.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "qmldir.designer_supported.v1",
        languages: &["qmldir"],
        query_family: "qmldir",
        description: "A Designer support declaration from a qmldir manifest.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key("directive", STR, ALWAYS, "The manifest directive name."),
            key(
                "supported",
                BOOL,
                ALWAYS,
                "Whether Designer support is enabled.",
            ),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "qmldir.static.v1",
        languages: &["qmldir"],
        query_family: "qmldir",
        description: "A `static` directive: the module is available only as a static library.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key("directive", STR, ALWAYS, "The manifest directive name."),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "qmldir.system.v1",
        languages: &["qmldir"],
        query_family: "qmldir",
        description: "A `system` directive: the module is a system module.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key("directive", STR, ALWAYS, "The manifest directive name."),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "qmldir.prefer.v1",
        languages: &["qmldir"],
        query_family: "qmldir",
        description: "A preferred QML resource path declaration.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key("directive", STR, ALWAYS, "The manifest directive name."),
            key("path", STR, ALWAYS, "The preferred resource path."),
        ],
    },
    StructuralFactPatternSpec {
        pattern_id: "qmldir.linktarget.v1",
        languages: &["qmldir"],
        query_family: "qmldir",
        description: "A linker target declaration from a qmldir manifest.",
        metadata_keys: &[
            K_PATTERN_VERSION,
            K_QUERY_FAMILY,
            key("directive", STR, ALWAYS, "The manifest directive name."),
            key("target", STR, ALWAYS, "The linker target path."),
        ],
    },
];
